//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Dreamscape
{
	public enum Position
	{
		top = 0,
		middle = 1,
		bottom = 2
	};
	
	public enum SortBy
	{
		alphabetically = 0,
		type = 1
	};
	
	public enum Target
	{
		deck = 0,
		hand = 1,
		field = 2,
		subconscious = 3
	};
}

